name: Compile and Test

on:
  push:
    branches:
      - "*"
      - '!main'

jobs:
  build:
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Build
          run: |
            mvn clean install


        - name: SonarQube Scan
          run: |
            mvn verify sonar:sonar -Dsonar.host.url=$SONARQUBE_URL -Dsonar.token=$SONARQUBE_TOKEN -Dsonar.qualitygate.wait=true
          env:
            SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
            SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
